runatlantis/terraform-gce-atlantis

examples/basic/README.md, examples/complete/README.md
* Updated the DNS documentation to include a reference for non Cloud DNS users.
* There's a high chance that people manage their DNS outside of GCP.
=> Update DNS docs

.github/auto-release.yml
* Add docs label to patch to prevent minor releases
=> Add `documentation` label to patch release

main.tf
Closes #65 
* To avoid breaking changes we should pin a version.
=> remove the terraform-google-modules/container-vm/google version constraint, hardpin a version

README.md, main.tf, startup-script.sh, variables.tf
* Added a variable called `tags`.
* Users should be able to assign tags to the instance running atlantis.
=> Add a `tags` variable

README.md
* Added an entry to the documentation that states that we don't route nor redirect any HTTP requests, and expect you to use HTTPS.
* HTTP is ancient.
* Provide the justifications for the changes
* Closes #75
=> Document that we don't route nor redirect any HTTP requests

README.md, main.tf, variables.tf
As proposed in #41, we should allow users to bring their own start-up script.
* Created a `startup_script` variable.
* Next to cloudinit, users should be able to execute their own startup script.
* Closes #41
=> Introduce startup script var

README.md, outputs.tf
* Added a few new outputs related to the COS image and managed SSL certificate.
* These could be useful to a user.
* Closes #39 .
=> Add cos image ID and managed SSL outputs

main.tf
* Substituted the static `atlantis` tag with a random 6 character string.
* Users might apply similar tags to different resources not coming from this module, the  tag we used was too generic.
* Closes #77
=> Fix static tagging

main.tf
Set `sample_rate` to `1` (default value) on `google_compute_backend_service` resource `log_config` block
When used as-is, the module is not idempotent, and results in change on each apply:
```
Terraform will perform the following actions:
~ resource "google_compute_backend_service" "default" {
id                              = "projects/argyle-security-admin/global/backendServices/atlantis"
name                            = "atlantis"
~ log_config {
- sample_rate = 1 -> null
}
}
Plan: 0 to add, 1 to change, 0 to destroy.
```
[google_compute_backend_service sample_rate documentation](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_backend_service#sample_rate)
The ideal solution would be to provide an input variable for setting both logging and its …
=> Fix module idempotency by setting sample_rate on backend service log_config

main.tf
* Use `google_netblock_ip_ranges` data source to retrieve health check IP ranges
* This will ensure IP ranges are always up to date, and don't have to be manually updated if it changes on GCP side
* [google_netblock_ip_ranges](https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/netblock_ip_ranges) terraform data source
=> Use data source to retrieve health check IP ranges

README.md
* Document `google_netblock_ip_ranges` data source added in https://github.com/bschaatsbergen/terraform-gce-atlantis/pull/88
* Trim whitespace & remove trailing punctuation
* Trailing punctuation in headers might be a matter of preference, but generally it is [suggested not to use it](https://cirosantilli.com/markdown-style-guide/#punctuation-at-the-end-of-headers)
* Removing it also makes all headings consistent
=> Document `google_netblock_ip_ranges` data source

main.tf
* Add `default_url_redirect` to `google_compute_url_map` when IAP is enabled
* Even with IAP enabled, if you go to load balancer IP, you're taken straight to Atlantis UI, bypassing any authentication. This is because by default unmatched requests are handled by the `default` service
* [google_compute_url_map#default_url_redirect](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_url_map#nested_default_url_redirect)
=> Add redirect to domain for unmatched requests

examples/iap_enabled/README.md, examples/iap_enabled/iap.tf, examples/iap_enabled/main.tf, examples/iap_enabled/server-atlantis.yaml, outputs.tf
This PR adds an additional output for the name of the IAP backend service, which is used as an input for the permissions binding used to gate access to the IAP-protected Atlantis deployment.
It also adds an additional example showing how to use IAP to protect Atlantis.
The output eliminates the need to pull the name of the service via a data source (which would require the name to get the data source, so...) which also helps Terraform determine order of operations.
IAP has enough extra configuration I thought it worthy of describing in more detail, especially since I suspect most people will not want to have their UI just hanging out there on the internet.
=> Adding IAP example and output for IAP backend service

.pre-commit-config.yaml
* ignore lock file for terraform-docs
* This maintains the `> x.y.z` qualifier in the readme docs for providers instead of reading resolved provider versions `a.b.c` directly from the lock file
* https://terraform-docs.io/
=> fix: ignore lock file for terraform-docs

README.md, main.tf
* When a container is given privileged mode it receives all permissions the host has, it's currently set to `true` but we should set it to `false` as it doesn't affect the atlantis installation.
* Doesn't affect the atlantis installation.
* Closes #102
=> Set `privileged` to `false`

examples/iap_enabled/iap.tf
```
╷
│ Error: Unsupported argument
│
│   on modules/atlantis/iap.tf line 16, in resource "google_iap_client" "atlantis":
│   16:   project      = var.project_id
│
│ An argument named "project" is not expected here.
╵
```
A small change to IAP example I found during my deployment
To make it work
* Use `Closes #123`, if this PR closes a GitHub issue `#123`
* If possible, link to the relevant documentation to add some context.
=> examples: remove project from google_iap_client

main.tf, variables.tf
* Adding variables for managing labels for GCP resources
* Having Labels for GCP resources are useful for billing / other tagging purpose
* https://cloud.google.com/compute/docs/labeling-resources
=> feat: add labels for gcp resources

README.md, main.tf, variables.tf
* Added an option to enable OS Login (off by default)
* OS Login allows to manage access to the VM using IAM permissions rather than injecting SSH keys each time. It was left off by default, but due to adding a new metadata key, this becomes a **breaking change as it will force re-creation of the instance**
* [OS Login documentation](https://cloud.google.com/compute/docs/oslogin/)
=> Add an ability to enable OS Login

main.tf
* Set `enable_secure_boot` to `true` (hardcoded)
* [Secure boot](https://cloud.google.com/compute/shielded-vm/docs/shielded-vm#secure-boot) is an additional security feature to harden the resulting VM -- since VTPM & integrity monitoring were already turned on by default, it only makes sense to have it on too
* Setting this value will force the instance to be recreated, so **this is a breaking change**
=> Enable secure boot

README.md, main.tf, variables.tf
* Machine image is now pinnable
* Check the difference between two commits. If we keep only the first commit then `full` image name needs to be passed everytime. After the second commit you can just provide the short name and it will be verified. One drawback is that this it's not possible to move away from cos images, which probably is not desired anyway.
* Not always you would want to stay on the latest cos image. Not always you want to update it if you're performing other changes.
* It also seems that not all latest `cos` images work well with atlantis/secure vm configurations.. Just today i was making tweaks to the module and latest image got deployed too. As a result backend never could be reached.. could not find any logs as to why this happened, but reverting the image instantly …
=> Allow pinning vm's machine image, instead of always using latest …stable/cos_cloud

README.md
* Adds a simple example of the Terraform Module Registry syntax.
* Makes it easier to implement as there's a bit of reference code.
* Closes #56
=> feat: add simple Terraform registry syntax example

README.md
* Fixed a typo in the IAP section related to oauth2 config.
* Closes #121
=> chore: fix typo in IAP example related to oauth2 config

README.md, examples/cloud-armor/README.md, examples/cloud-armor/main.tf, examples/cloud-armor/server-atlantis.yaml, main.tf, variables.tf
* Give clients the option to attach a security policy to the default backend service.
* Create a new deployment example, using IAP and Cloud Armor, allowing only events coming from GitHub Webhooks.
* Google Cloud Armor security policies to protect applications running behind a load balancer from distributed denial-of-service (DDoS) and other web-based attacks. It also features preconfigured security policies.
* Improve the security of the default backend service: even if the webhook secret is compromised, only requests coming from the whitelisted IPs are allowed.
* GitHub Webhook IPs: https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/about-githubs-ip-addresses
* Log4j preconfigured WAF rule: https://cloud.google.com/armor/docs/waf-rules
=> feat: add option to attach a security policy to the default backend

examples/cloud-armor/README.md
* Fix a typo in the README.
* It's referencing the incorrect example usage.
=> Minor fix in Cloud Armor README

README.md, examples/cloud-armor/README.md, examples/cloud-armor/main.tf, main.tf, variables.tf
This adds a variable which allows applying a Cloud Armor policy to the IAP backend service, in addition to the default.
We'd like to be able to restrict access to the Atlantis UI, even with IAP added.
This is basically just an extension of https://github.com/bschaatsbergen/terraform-gce-atlantis/pull/132 for the other backend.
=> Adding security policy variable for IAP backend

README.md, main.tf, variables.tf
* Give users the option to enable Confidential VM feature
* Confidential VMs ensure that data and applications stay private and encrypted even while in use. This PR gives users the option to enable this feature and improve their security strategy.
* This feature is disabled by default to maintain backwards compatibility, and because Confidential VMs do not support live migration: https://cloud.google.com/confidential-computing/confidential-vm/docs/error-messages#live_migration_isnt_supported
* Confidential Computing - https://cloud.google.com/confidential-computing/confidential-vm/docs/about-cvm
=> feat: add option to enable confidential vm

README.md, examples/shared-vpc/README.md, examples/shared-vpc/main.tf, examples/shared-vpc/server-atlantis.yaml, main.tf, variables.tf
* Give users the option to deploy in shared vpc architectures
* When enabled, the firewall rule and default route are not created, and the host project id is used in the  instance template's network configuration.
* Create a new example using this feature under `examples/shared_vpc`
* These changes allow this module to be deployed in projects that use Shared VPC
* https://cloud.google.com/iap/docs/using-tcp-forwarding#create-firewall-rule
* https://cloud.google.com/load-balancing/docs/health-checks#fw-rule
* https://cloud.google.com/load-balancing/docs/l7-internal/l7-internal-shared-vpc#configure_firewall_rules
* Close #110
> Let me know how you feel about these changes and the accompanied example 😄
=> feat: shared vpc support

.github/workflows/ci.yaml
* Add `repository` to `actions/checkout` step in `ci.yml`
* Currently, the action will not work for PRs coming from forks, as it defaults to `github.repository`
* Default value - https://github.com/actions/checkout/blob/cd7d8d697e10461458bc61a30d094dc601a8b017/action.yml#L6
* https://docs.github.com/en/webhooks/webhook-events-and-payloads?actionType=opened#pull_request
* Looks like this is a common issue
* https://github.com/actions/checkout/issues/551
* https://github.com/actions/checkout/issues/455
=> fix: add repository to checkout step in ci.yml

main.tf
*  google_logging_enabled variable now correctly passed to instance template
* `google_monitoring_enabled` was used instead of `google_logging_enabled` to set the instance template `google-logging-enabled`
* Close #129
=> fix: google_logging_enabled variable now correctly passed to instance template

.github/workflows/ci.yaml
* Disable terraform-docs push when on forks
* Use [`ghcommit-action`](https://github.com/planetscale/ghcommit-action) to create a verified commit and push the changes, instead of using terraform-docs' `git-push`, [which does not sign commits](https://github.com/terraform-docs/gh-actions/pull/110)
* Set `continue-on-error` to `true` since we only commit in the next step
* Add instructions to run tfdocs locally for forks in workflow summary
* The `ci` workflow fails when running on forks because it fails to push changes (as it should): https://github.com/runatlantis/terraform-gce-atlantis/actions/runs/8737454606/job/24044031175
* The commits being signed/verified are really useful when people's forks live inside organizations that require signed commits (rebasing and pushing unsigned …
=> chore: disable terraform-docs push when on forks and sign commit

.github/workflows/ci.yaml, README.md, main.tf, variables.tf
* Give users the option to expose the `/healthz` endpoint from the default (non-IAP) backend
* This allows users to create url-based Uptime Checks targeting `/healthz`
* https://cloud.google.com/monitoring/api/resources#tag_uptime_url
* https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/monitoring_uptime_check_config
=> feat: add option to expose /healthz without IAP

README.md, main.tf, variables.tf
* Add variable to allow changing the type of the persistent disk
* The module forces users to use `pd-ssd`s
* Close #158
=> feat: add persistent_disk_type variable

.github/workflows/ci.yaml, .terraform-docs.yml
* Remove version from docker run tf docs suggestion
* Set `lockfile: false` in terraform-docs settings
* When running the suggested command to locally generate docs, there is a difference in behavior between local and remote (gh action) results, since locally it has access to the terraform lockfile.
* Since we do not commit the lockfile, it has no effect in gh workflows
* https://github.com/terraform-docs/gh-actions/issues/98
=> chore: fix terraform docs behavior

README.md, main.tf, variables.tf
continuation of: https://github.com/runatlantis/terraform-gce-atlantis/pull/149
Achieve pinning of COS image by fixing behavior of machine_image var and input to downstream container module
* Be able to pin image and not always use latest one
* Closes #114 (which needs to be reopened to be closed again with this)
=> Fix pinning of machine_type #2

examples/secure-env-vars/custom-entrypoint.sh.tftpl
* Allow the atlantis user to write to the key file
* Prevent an error when the VM is recreated.
=> chore: fix key file permissions custom-entrypoint.sh.tftpl in secure example

examples/secure-env-vars/README.md
The README still references some non-existent workflows, which I believe were removed in favor of the custom entrypoint bash script that manages the environment variables.
=> remove non existent links
